import { StyleSheet } from "react-native";
import {
    responsiveFontSize as RF,
    responsiveHeight as hp,
    responsiveWidth as wp,
  } from 'react-native-responsive-dimensions';
    import colors from '../../constants/colors';
    import fonts from '../../constants/fonts';

export default StyleSheet.create({
    loginContainer: {
        backgroundColor: '#fff',
        width: wp(100),
        height: hp(100),
        alignItems: 'center',
        marginBottom:hp(1),
      },
      logo: {
        width:wp(30),
        marginTop: hp(5),
        resizeMode:'contain',
        height:wp(30),
        marginBottom:hp(5),
      },
      LgView: {
        width: wp(100),
        height: hp(12),
        alignItems: 'center',
      },
      fLgView: {
        width: wp(100),
        height: hp(20),
        alignItems: 'center',
        marginTop:hp(5),
        marginBottom:hp(15),
      },
      fLgcView:{
        width: wp(100),
        height: hp(20),
        alignItems: 'center',
        marginTop:hp(5),
        marginBottom:hp(10),
      },
      loginText: {
        fontSize: RF(3),
        marginTop:hp(10),
        color:'black',
        fontWeight:'bold',
        fontFamily:fonts.poppinsBold,
      },
      input: {
        height: hp(7),
        fontSize: RF(2),
        paddingLeft:wp(2),
        color: 'black',
        backgroundColor:'white',
        width:wp(80),
        marginHorizontal:wp(10),
        borderWidth: 1,
        borderColor: 'gray',
        borderRadius: wp(4),
        fontFamily:fonts.poppinsRegular,
        marginVertical:hp(1),
        flexDirection:'row',
      },
      inputbox: {
        height: hp(6.5),
        fontSize: RF(2),
        color: 'black',
        backgroundColor:'white',
        width:wp(65),
        fontFamily:fonts.poppinsRegular,
        justifyContent:'center',
        borderRadius: wp(3),
      },
      loginBtnText: {
        fontSize: RF(2.4),
        textAlign: 'center',
        justifyContent: 'center',
        color: 'white',
        fontFamily:fonts.poppinsBold,
      },
      logBtn: {
        justifyContent: 'center',
        width: wp(80),
        height: hp(8),
        borderRadius: wp(4),
        marginVertical:hp(2),
        marginHorizontal:wp(10),
        backgroundColor: colors.MAIN_THEME,
      },
      forgotTxt: {
        fontSize: RF(2),
        color: 'black',
        textAlign:'center',
        justifyContent:'center',
        marginLeft:wp(3),
        fontFamily:fonts.poppinsRegular,
      },
      reset: {
        fontSize: RF(2),
        color: 'blue',
        textAlign:'center',
        justifyContent:'center',
        marginLeft:wp(3),
        fontFamily:fonts.poppinsRegular,
      },
      acountTxt: {
        fontSize: RF(1.8),
        color: 'black',
        textAlign:'center',
        justifyContent:'center',
        marginTop:hp(1),
        fontFamily:fonts.poppinsRegular,
      },
      signupTxt: {
        fontSize: RF(1.8),
        color: 'red',
        marginTop:hp(1),
        textAlign:'center',
        justifyContent:'center',
        fontFamily:fonts.poppinsRegular,
        fontWeight:'bold',
      },
      codeInput: {
        borderWidth: 10,
        borderRadius:10,
        borderColor: 'gray',
        padding: 10,
        margin: 10,
      },
      inputBoxaa: {
        borderWidth: 1,
        borderRadius: 10,
        borderColor: 'gray',
        padding: 10,
        margin: 10,
      },
      topiP:{
        textAlign:'center',
        fontSize:RF(3),
        color:'black',
        marginTop:hp(4),
      },
      disP:{
        textAlign:'center',
        fontSize:RF(1.5),
        color:'gray',
        marginTop:hp(20),
      },
      disPa:{
        textAlign:'center',
        fontSize:RF(1.5),
        color:'gray',
      },
      wText:{
        textAlign:'center',
        fontWeight:'600',
        fontSize:RF(1.5),
        color:"#79197E",
        marginBottom:hp(20),
      },
      TWText:{
        textAlign:'center',
        fontWeight:'400',
        fontSize:RF(2),
        color:'#2A2D32',
        width:wp(70),
      },
      container: {
        width: wp(90),
        height: hp(40),
        marginHorizontal:wp(5),
      },
      wrapper: {},
      slide: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      imagew: {
        width: wp(80),
        height: hp(28),
        marginVertical:wp(10),
      },
      titleText:{
        color: 'black', 
        fontSize: RF(1.8),
        fontFamily:fonts.poppinsMedium,
        textAlign:'center',
      },
      eye:{
        width:wp(5),
        resizeMode:'contain',
        alignItems:'center',
        justifyContent:'center',
        marginTop:hp(1),
        marginLeft:wp(2),
      },
    

});