const colors = {

MAIN_THEME:'#2697FF',
MAIN_THEME_LIGHT:'#24F4FF',
MAIN_THEME_CHARM_LIGHT:'#1CD0FF',
MAIN_THEME_DARK:'#3A75FF',

WHITE_COLOR:'#FFFFFF',
BLACK_COLOR:'#000000',

SILVER_COLOR:'#C4C4C4',
RED_COLOR:'red',

};
export default colors;